# Generated by Django 4.2.6 on 2023-10-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactUS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=63)),
                ("email", models.EmailField(max_length=150)),
                ("subject", models.CharField(max_length=225)),
                ("message", models.TextField()),
            ],
        ),
    ]
